title: Your awesome title
author: Foo Bar
email: foo@bar.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to this blog 

# social links
twitter_username: @sometweep
github_username:  fsfarah

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
